### ISSUE TITLE
 could not convert string to float: Id

### ISSUE THREAD

**Issue by ericbodden** [abramhindle/organize-conference-sessions-by-paper-topics#1]
Hello.

When downloading and running your script I am seeing the error below. Did the metadata file format change somehow?

Cheers
Eric

$ python msrcluster.py

filtering tokens
out
predictions = out/lda-predictions.dat
Num weight bits = 14
learning rate = 0.5
initial_t = 1
power_t = 0.5
decay_learning_rate = 1
creating cache_file = out/lda-topics.dat.cache
Reading datafile = out/lda-vr_lda_input.lda.txt
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
9.739354 9.739354            1            1.0  unknown   0.0000     1284
9.725735 9.712116            2            2.0  unknown   0.0000      630
9.729002 9.732268            4            4.0  unknown   0.0000     1146
9.731507 9.734013            8            8.0  unknown   0.0000      533
10.343201 10.954895           16           16.0  unknown   0.0000     1459
10.648250 10.953299           32           32.0  unknown   0.0000      804
10.801102 10.953954           64           64.0  unknown   0.0000     1193
9.782553 8.764004          128          128.0  unknown   0.0000      987
8.953733 8.124913          256          256.0  unknown   0.0000      554
8.414667 7.875602          512          512.0  unknown   0.0000      533

finished run
number of examples = 720
weighted example sum = 720.000000
weighted label sum = 0.000000
average loss = 0.000000 h
total feature number = 723020
token count at summary create 9503
find token topic associations
Traceback (most recent call last):
  File "msrcluster.py", line 47, in <module>
    summary = vw.create_summary()
  File "/private/tmp/organize-conference-sessions-by-paper-topics/lda.py", line 311, in create_summary
    summary.set_token_topic_associations)
  File "/private/tmp/organize-conference-sessions-by-paper-topics/lda.py", line 338, in read_vowpal_output
    topic_associations = map(float, line)
ValueError: could not convert string to float: Id

**Comment by ericbodden** [comment]
Also, by the way, EasyChair does not directly allow (any more?) the export of the required CSV file, it seems. Instead it produces an xlsx file using those headers:

`# Authors Title paper Latex-source LNI-Rechtseinräumung Time Decision`

**Comment by abramhindle** [comment]
What version of vowpal wabbit are you running?

````
$ vw --version
8.1.1
````

Also it seems to be a premium option in conference data download to get CSV and XLSX files.

**Comment by ericbodden** [comment]
Hi @abramhindle 
I am using version 8.5.0.
The CSV file I now crafted myself for my conference. But the script currently also fails with the CSV file you are providing.

**Comment by abramhindle** [comment]
8.5.0 is so new that I can't build it on ubuntu 16.04 so I cannot test it.

Try installing the https://github.com/JohnLangford/vowpal_wabbit/releases/tag/8.1.1 or https://github.com/JohnLangford/vowpal_wabbit/archive/8.1.tar.gz 

I think the output format of 8.5 is different than 8.1

**Comment by ericbodden** [comment]
Hmm, I am afraid that seems to be not so simple, as it screws up the dependencies. On my Mac I now get:

$ autoreconf --force --install
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:16: installing './compile'
configure.ac:4: installing './missing'
Makefile.am: error: required file './README' not found
cluster/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

**Comment by ericbodden** [comment]
Update: After reinstalling glibtool I now get:

$ autoreconf --force --install
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'acinclude.d'.
glibtoolize: copying file 'acinclude.d/libtool.m4'
glibtoolize: copying file 'acinclude.d/ltoptions.m4'
glibtoolize: copying file 'acinclude.d/ltsugar.m4'
glibtoolize: copying file 'acinclude.d/ltversion.m4'
glibtoolize: copying file 'acinclude.d/lt~obsolete.m4'
configure.ac:16: installing './compile'
configure.ac:4: installing './missing'
Makefile.am: error: required file './README' not found
cluster/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

**Comment by abramhindle** [comment]
Hi Eric, I hope I'm not too late. 

I modified the parser to handle new vowpal wabbit output and it seems to work.

The format of the CSV file doesn't matter other than the first column is to match the IDs of the files. So you can have whatever metadata you want. So please download the new version and try again.

**Comment by ericbodden** [comment]
Thanks a lot, that did it!

**Comment by abramhindle** [comment]
OK that's great Erci! Remember it's k-means so you can run it a few times till you like the results :)
